### ISSUE TITLE
.scss文件不支持@import 吗

### ISSUE THREAD

**Issue by taoWcode** [kszitt/react-native-sass-to-stylesheet#1]
我使用一个params.scss 放置变量，@import params.scss后   使用params.scss中的变量报`(node:26088) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null`;

是否是不支持，如果不支持，这个变量的价值不大。

还有什么时候能支持继承，这个功能我在看到react-native-sass-transformer里面支持，但是里面的功能相对于react-native-sass-to-stylesheet 缺少适配方法以及嵌套等。

很感谢你把这个插件分享出来，给了我很大的便利。

**Comment by kszitt** [comment]
@taoWcode 感谢使用该项目，并提出问题。
你说的这个问题，我本地测试得没问题。方便把params.scss定义变量，如何使用的代码贴出来吗？我好排查问题

**Comment by kszitt** [comment]
@taoWcode 感谢你使用该项目，会在下个版本增加@import功能，并且通知你。

**Comment by kszitt** [comment]
@taoWcode 现在scss文件已经支持@import功能，请升级到最新版体验。
