### ISSUE TITLE
template文件怎么配置 配置了不起作用 

### ISSUE THREAD

**Issue by lzd358194530** [kszitt/react-native-sass-to-stylesheet#2]
template文件怎么配置 配置了不起作用

**Comment by kszitt** [comment]
感谢你的使用。请通过以下几点解决问题：
1、启动文件`toStyle.js`(你的启动文件可能不叫这个，不过没影响)，必须在项目根目录下。
2、template文件也必须在项目根目录下。
3、如果你的template文件名为`template.js`，那么不需要配置`options.templatePath`。否则请初始化时，配置`options.templatePath`。例如，template文件名为“youTemplate.js”，可以使用以下配置：
``` javascript
ToStyles.init(<监听目录>, {
  templatePath: "./youTemplate.js"
});
```
4、如果还没有解决问题，请联系我
