### ISSUE TITLE
希望能够支持 scss 语法 

### ISSUE THREAD

**Issue by lzd358194530** [kszitt/react-native-sass-to-stylesheet#3]
目前好像只能支持 变量 
不支持 function mixin placeholder  include extend 等  能不能把sass loader整合进去

**Comment by kszitt** [comment]
sass loader整合不过去
加`function mixin placeholder include extend`的工作量太大，后面可能慢慢加
感谢你提的需求。

**Comment by lzd358194530** [comment]
还有@imort 的路径问题 不能写相对路径 比较怪

**Comment by kszitt** [comment]
@lzd358194530 支持相对路径的。请参照本项目`temple/src/style.scss`的用法使用。
也可以下载本项目到本地运行，在根目录执行`node temple/toStyles.js`或者`npm run temple`，查看生成的文件。
