### ISSUE TITLE
想问一下，css转RN样式应用的场景有哪些呢

### ISSUE THREAD

**Issue by AZQD** [kszitt/react-native-sass-to-stylesheet#6]
想问一下，css转RN样式应用的场景有哪些呢，另外，有没有react转react native的实现方案或思路，谢谢！

**Comment by kszitt** [comment]
这个插件是react native框架专用的，通过编写css文件自动转换成react native的样式文件。
react native写样式的格式比较繁琐，对于WEB出身的开发者，习惯写css样式，写react native样式很不习惯，所以就写了这个插件。

**Comment by kszitt** [comment]
react和react native属于不同的框架，好像没法儿转换。

**Comment by AZQD** [comment]
感谢作者解答~
